### ISSUE TITLE
How to use the model

### ISSUE THREAD

**Issue by TQuy** [magizbox/underthesea.chunking#1]
I want to know how to use the model to annotate chunk tags given word segmentation and pos tags

**Comment by rain1024** [comment]
You can run pre-trained chunking model by using underthesea 

```
>>> # -*- coding: utf-8 -*-
>>> from underthesea import chunk
>>> text = 'Bác sĩ bây giờ có thể thản nhiên báo tin bệnh nhân bị ung thư?'
>>> chunk(text)
[('Bác sĩ', 'N', 'B-NP'),
 ('bây giờ', 'P', 'I-NP'),
 ('có thể', 'R', 'B-VP'),
 ('thản nhiên', 'V', 'I-VP'),
 ('báo tin', 'N', 'B-NP'),
 ('bệnh nhân', 'N', 'I-NP'),
 ('bị', 'V', 'B-VP'),
 ('ung thư', 'N', 'I-VP'),
 ('?', 'CH', 'O')]
```

**Comment by TQuy** [comment]
> You can run pre-trained chunking model by using underthesea
> 
> ```
> >>> # -*- coding: utf-8 -*-
> >>> from underthesea import chunk
> >>> text = 'Bác sĩ bây giờ có thể thản nhiên báo tin bệnh nhân bị ung thư?'
> >>> chunk(text)
> [('Bác sĩ', 'N', 'B-NP'),
>  ('bây giờ', 'P', 'I-NP'),
>  ('có thể', 'R', 'B-VP'),
>  ('thản nhiên', 'V', 'I-VP'),
>  ('báo tin', 'N', 'B-NP'),
>  ('bệnh nhân', 'N', 'I-NP'),
>  ('bị', 'V', 'B-VP'),
>  ('ung thư', 'N', 'I-VP'),
>  ('?', 'CH', 'O')]
> ```

Can I do it without word segmentation step, because changing the word segmentation disrupts the training and testing proccess. In addition, where can I import underthesea library
`from underthesea import chunk`

**Comment by rain1024** [comment]
You can install underthesea via pip

```
pip install underthesea
```

If you want to do chunking witthout word segmentation, I encourge you examine code in this repo and implement your own pipeline. Good luck
